### ISSUE TITLE
Impossible to scroll menu if there are too many elements.

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-escapade-theme#22]
For long menu (or on mobile) if there are too many elements then we are unable to reach them since we can't scroll.

**Comment by chriswallace** [comment]
Fixed in d6c68026200bfa3ac3bbc6904ce1a26003e8881e

**Comment by jjtuttle** [comment]
I have v .0.9.0 and I see on gihub there is a v 1.0.0 (which fixed the menu scroll issue from < v 1.0.0). BUT wordpress shows ALL up to date even when I click check... How can I get this v 1.0.0 up and working with the scrolling menu too? just zip and reinstall over old version?

**Comment by EvanHerman** [comment]
Hi @jjtuttle,

We haven't released version 1.0.0 to the repository yet, that's why you're not seeing the updates. To update, you can simply replace the theme found here in github with the theme in your themes directory. You should still receive future updates, moving forward.

**Comment by jjtuttle** [comment]
What then do I need to change to make the navigation work?

I tried to activate the new version but in preview mode I noticed I lost all my stuff. So I did not activate it. I need to only fix the side man to scroll. 

Thank you,
James Tuttle

**Comment by EvanHerman** [comment]
Hi @jjtuttle,

The navigation is stored in the database, so manually overwriting the theme to the most up to date version shouldn't be affecting the navigation (items or order). Did you overwrite the theme, or did you activate it alongside your child theme?

I would recommend taking a backup of your existing theme, and then manually overwriting the files for this plugin, so you only have one copy installed.

**Comment by jjtuttle** [comment]
I did a backup 

I am not familiar on this type of them thing yet. Came from other web designs ways. 

Is there a good knowledge base on doing what you said? I don't want to pester you on this type of issue. Just wanted to get the nag menu to scroll since we added 3 more pages and now the 3 are not seen by the customer and clients. 

So I did nothing that you mentioned not know how, I just need to find an article on doing that?

Your thoughts?

Thanks again for your prompt reply 😀💯

Thank you,
James Tuttle
